- hosts: raspi
  remote_user: pi
  become: yes
  
  tasks:
  - name: Update all packages
    apt:
      update_cache: yes
      upgrade: yes
  
  - name: Reboot PI
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for PI to reboot
    local_action:
      module: wait_for
        host="{{ ansible_hostname }}"
        port=22
        state=started
        delay=5
