- hosts: raspi
  remote_user: pi
  become: yes
  
  tasks:
  - name: Install VIM Editor
    apt:
      name: vim
      state: present
  - name:
    apt
     name: git
     state: latest
  - name: Install/Update node.js
    apt:
      name: nodejs
      state: present
  - name: Install nmap
    apt:
      name: nmap
      state: present
  - name: Install MongoDB
    apt:
      name: mongodb
      state: present
