- hosts : raspi
  remote_user: pi
  become: yes
  
  vars:
    wifi_pass_hash: "{{ wpa_pass.stdout }}"
  
  vars_prompt:
  - name: "wifi_ssid"
    prompt: "Enter WiFi SSID"
    default: "SinhaWeb"
    private: no
   
  - name: "wifi_pass"
    prompt: "Enter WiFi password"
    private: yes

  tasks:
  - name: Obtain password hash
    shell: wpa_passphrase {{ wifi_ssid }} {{ wifi_pass }} | sed -n 4p | cut -d'=' -f2
    register: wpa_pass
  
  - name: Create WiFi config file
    template:
       src: ../template/wpa_supplicant.conf.j2
       dest: /etc/wpa_supplicant/wpa_supplicant.conf
       owner: root
       group: root
       mode: 0600
    ignore_errors: yes
  
  - name: Reboot PI
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for PI to reboot
    local_action:
      module: wait_for
        host="{{ ansible_hostname }}"
        port=22
        state=started
        delay=5
